### ISSUE TITLE
Java wrapper possible?

### ISSUE THREAD

**Issue by Chris2011** [atom/teletype-client#40]
Hi,

I found your very nice product. It sounds very great and seems to be fun to use it. What I want to know is, is it possible to create a java wrapper for this, so that I can use it in an other editor or IDE, which is based on Java, for example?

Regards

Chris

**Comment by LordZardeck** [comment]
Yeah, i would love something like this in my PHPStorm or WebStorm editor

**Comment by jasonrudolph** [comment]
> What I want to know is, is it possible to create a java wrapper for this, so that I can use it in an other editor or IDE, which is based on Java, for example?

We'd love to see that happen!  As described in the [blog post announcing Teletype for Atom](https://blog.atom.io/2017/11/15/code-together-in-real-time-with-teletype-for-atom.html#editor-agnostic-client-library):

>> **Editor-agnostic client library**: The Teletype Atom package implements UI components and Atom-specific integration code, but most of the logic lives in an editor-agnostic library called [teletype-client](https://github.com/atom/teletype-client). Our protocols and API may churn for a while as we develop the system, but it should be possible to integrate teletype-client into any web-based application or even package it in an Electron-based server to talk to it from native editors. Supporting inter-operation between different text editors is definitely part of our long term vision.

We'd love to interoperate with other text editors. In the near term, bringing Teletype to more text editors will likely require the help of engineers that are familiar with creating packages for those text editors. Because of this, and because a Java-based wrapper would probably be a separate project in a separate repository, and because we treat our issues list as [our backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), I'm going to close this issue to keep the _teletype-client_ backlog clean and focused. 😅

**Comment by Chris2011** [comment]
Thx for clarification.
